#DEVROOT			=	$(HOME)/dev
#DEVMAKE			=	$(DEVROOT)/make

#cflags			=	-I../include
#target			=	test-convert.exe
#sources			=	$(wildcard *.cpp)

#include $(DEVMAKE)/makefile



all: $(wildcard *.cpp) 
	g++ *.cpp -I../include -I../../boost_1_55_0

